apiVersion: v1
data:
  config.yaml: |
    prowjob_namespace: default
    pod_namespace: test-pods
    #log_level: debug

    sinker:
      max_pod_age: 10h0m0s
      max_prowjob_age: 24h0m0s
      resync_period: 0h20m0s

    plank:
      default_decoration_config:
        utility_images: # using the tag we identified above
          clonerefs: "gcr.io/k8s-prow/clonerefs:v20190909-c3ac80e32"
          initupload: "gcr.io/k8s-prow/initupload:v20190909-c3ac80e32"
          entrypoint: "gcr.io/k8s-prow/entrypoint:v20190909-c3ac80e32"
          sidecar: "gcr.io/k8s-prow/sidecar:v20190909-c3ac80e32"
        gcs_configuration:
          bucket: prow-artifacts # the bucket we just made
          path_strategy: explicit
        gcs_credentials_secret: gcs-credentials # the secret we just made

    presubmits:
      ironreality/kuard:
      - name: kuard-build-push-pipeline
        decorate: false
        always_run: true
        skip_report: false
        namespace: test-pods
        agent: tekton-pipeline
        pipeline_run_spec:
          pipelineRef:
            name: kuard-build-push-pipeline
          serviceAccountName: build-bot
          resources:
          - name: git-source
            resourceRef:
              name: PROW_IMPLICIT_GIT_REF
          - name: docker-image
            resourceRef:
              name: kuard-image-repo-resource

    postsubmits:
      ironreality/kuard:
      - name: kuard-build-push-pipeline
        decorate: false
        always_run: true
        skip_report: false
        namespace: test-pods
        agent: tekton-pipeline
        pipeline_run_spec:
          pipelineRef:
            name: kuard-build-push-pipeline
          serviceAccountName: build-bot
          resources:
          - name: git-source
            resourceRef:
              name: PROW_IMPLICIT_GIT_REF
          - name: docker-image
            resourceRef:
              name: kuard-image-repo-resource

kind: ConfigMap
metadata:
  name: config
  namespace: default
