apiVersion: v1
data:
  username: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  password: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
kind: Secret
metadata:
  name: minio-access-secret
  namespace: test-pods
type: Opaque
---
apiVersion: v1
data:
  username: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  password: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
kind: Secret
metadata:
  name: minio-access-secret
  namespace: argo
type: Opaque
