apiVersion: v1
appVersion: master
description: MinIO is a high performance distributed object storage server, designed
  for large-scale private cloud infrastructure.
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: hello@acale.ph
  name: Acaleph
- email: dev@minio.io
  name: Minio
name: minio
sources:
- https://github.com/minio/minio
version: 3.0.7
