apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: argo-ui
  namespace: argo
spec:
  rules:
  - host: argo.example.com
    http:
      paths:
      - backend:
          serviceName: argo-ui
          servicePort: 80
        path: /
